export const fanCategories = [
  "behind a common thing",
  "habit",
  "word",
  "phenomenon",
  "everyday object",
  "cultural tradition",
  "food item",
  "piece of clothing",
  "invention",
  "animal behavior",
  "musical instrument",
  "holiday",
  "sport",
  "technology",
  "dance style",
  "game",
  "art movement",
  "architectural style",
  "weather event",
  "plant",
  "tool",
  "famous landmark",
  "children’s toy",
  "social custom",
  "color",
  "number",
  "symbol",
  "fashion trend",
  "vehicle",
  "board game",
  "body language",
  "street food",
  "advertising slogan",
  "old profession",
  "festival",
  "wild animal",
  "cats",
  "dogs",
];

export const scienceCategories = [
  "scientific phenomenon",
  "historical event",
  "common concept",
  "technological breakthrough",
  "astronomical discovery",
  "biological process",
  "engineering innovation",
  "medical advancement",
  "geological feature",
  "wild animal",
  "cats",
  "dogs",
  "writing system",
  "literary genre",
  "architectural style",
  "natural feature",
];

export const premiumCategories = {
  health: [
    "healthy lifestyle",
    "balanced nutrition",
    "physical activity",
    "mental health",
  ],
  motivation: [
    "goal achievement",
    "personal growth",
    "career success",
    "self-development",
  ],
};
